"""
Council Workflow Commands - 六步工作流CLI命令

统一简洁的命令接口:
- council init      生成 CLAUDE.md
- council plan      只读计划模式  
- council audit     全库审计
- council tdd       TDD测试生成
- council execute   沙盒执行
- council rewind    快照备份
- council clear     会话清理
"""

import os
from pathlib import Path
from datetime import datetime
from typing import Optional

from council.agents.base_agent import ModelConfig


def init_command(output_path: str = "CLAUDE.md") -> str:
    """
    /init - 自动扫描生成 CLAUDE.md
    
    Args:
        output_path: 输出文件路径
        
    Returns:
        生成的内容
    """
    from council.workflow.audit_phase import FullRepoScanner
    
    scanner = FullRepoScanner()
    scan_result = scanner.scan()
    
    content = f"""# CLAUDE.md - 项目规范 (自动生成)

> **Strictly follow the rules in ./AGENTS.md**
> **Generated at**: {datetime.now().strftime("%Y-%m-%d %H:%M")}

## 项目概览

- **文件总数**: {scan_result.get("total_files", 0)}
- **扫描时间**: {scan_result.get("scanned_at", "")}

## 技术栈

| 组件 | 技术 |
|------|------|
| **语言** | Python 3.12+ |
| **类型** | Pydantic v2 |
| **测试** | pytest |
| **Lint** | ruff |

## 构建命令

```bash
pytest tests/ -v
ruff check .
```

## 模型配置

| Agent | 模型 |
|-------|------|
| Orchestrator | {ModelConfig.CLAUDE_OPUS} |
| Coder | {ModelConfig.GEMINI_FLASH} |
| Auditor | {ModelConfig.CODEX} |

---
**Auto-generated by Council CLI**
"""
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"✅ Generated {output_path}")
    return content


def plan_command(task: str) -> dict:
    """
    /plan - 只读计划模式
    
    Args:
        task: 任务描述
        
    Returns:
        计划结果
    """
    from council.workflow.pm_phase import RequirementParser, TaskTreeGenerator
    
    parser = RequirementParser()
    generator = TaskTreeGenerator()
    
    requirement = parser.parse(task)
    task_tree = generator.generate(requirement)
    
    print("📋 任务计划:")
    for node in task_tree:
        print(f"  - [{node.id}] {node.title} ({node.assigned_agent})")
    
    return {
        "requirement": requirement,
        "task_tree": [{"id": n.id, "title": n.title} for n in task_tree],
    }


def audit_command(target_dir: str = ".") -> dict:
    """
    /audit - 全库审计 (Gemini Pro)
    
    Args:
        target_dir: 目标目录
        
    Returns:
        审计结果
    """
    from council.workflow.audit_phase import FullRepoScanner
    
    print(f"🔍 正在扫描 {target_dir} (使用 {ModelConfig.GEMINI_PRO})...")
    
    scanner = FullRepoScanner(root_dir=target_dir)
    result = scanner.scan()
    
    print(f"✅ 扫描完成: {result.get('total_files', 0)} 个文件")
    
    return result


def tdd_command(feature: str) -> dict:
    """
    /tdd - TDD测试生成 (Claude Sonnet)
    
    Args:
        feature: 功能描述
        
    Returns:
        生成的测试
    """
    from council.workflow.tdd_phase import TestGenerator
    
    print(f"🧪 正在生成测试 (使用 {ModelConfig.CLAUDE_SONNET})...")
    
    generator = TestGenerator()
    tests = generator.generate(feature)
    
    print(f"✅ 生成 {len(tests)} 个测试用例:")
    for test in tests:
        print(f"  - {test.name}")
    
    return {"tests": [{"id": t.id, "name": t.name} for t in tests]}


def execute_command(task: str, sandbox: str = "docker") -> dict:
    """
    /execute - 沙盒执行
    
    Args:
        task: 任务描述
        sandbox: 沙盒类型 (docker, local)
        
    Returns:
        执行结果
    """
    from council.workflow.executor_phase import PTCExecutor
    
    print(f"🚀 正在执行 (沙盒: {sandbox})...")
    
    executor = PTCExecutor(sandbox_type=sandbox)
    result = executor.execute(task, {})
    
    print(f"{'✅' if result.success else '❌'} {result.output_summary}")
    print(f"   Token 节省: {result.token_saved:.1%}")
    
    return {
        "success": result.success,
        "summary": result.output_summary,
        "token_saved": result.token_saved,
    }


def rewind_command(snapshot_id: Optional[str] = None) -> str:
    """
    /rewind - 快照备份
    
    Args:
        snapshot_id: 快照ID (默认自动生成)
        
    Returns:
        快照文件路径
    """
    from council.workflow.persistence import SessionSnapshot
    
    sid = snapshot_id or f"snap_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    
    snapshot = SessionSnapshot(
        snapshot_id=sid,
        task_summary="手动快照",
        files_modified=[],
        context={},
    )
    
    filepath = snapshot.save()
    print(f"📸 快照已保存: {filepath}")
    
    return filepath


def clear_command(keep: int = 5) -> dict:
    """
    /clear - 会话清理
    
    Args:
        keep: 保留快照数量
        
    Returns:
        清理结果
    """
    from council.workflow.persistence import ContextCleaner
    
    cleaner = ContextCleaner()
    result = cleaner.clear(keep_snapshots=keep)
    
    print(f"🧹 已清理 {result['deleted']} 个快照, 保留 {result['kept']} 个")
    
    return result


__all__ = [
    "init_command",
    "plan_command", 
    "audit_command",
    "tdd_command",
    "execute_command",
    "rewind_command",
    "clear_command",
]
