#!/usr/bin/env python3
"""
Council API Keys 配置向导

交互式设置 Anthropic、OpenAI、Google API keys
"""

import os
import sys
from pathlib import Path


def setup_env_file():
    """创建或更新 .env 文件"""
    env_path = Path(__file__).parent.parent / ".env"

    existing_keys = {}
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if "=" in line and not line.startswith("#"):
                    key, value = line.split("=", 1)
                    existing_keys[key] = value

    print("\n" + "=" * 60)
    print("  Council API Keys 配置向导")
    print("=" * 60)
    print("\n按 Enter 跳过已设置的 key，输入新值覆盖\n")

    keys_to_set = [
        ("ANTHROPIC_API_KEY", "Anthropic (Claude)", "sk-ant-..."),
        ("OPENAI_API_KEY", "OpenAI (GPT)", "sk-..."),
        ("GEMINI_API_KEY", "Google Gemini", "AI..."),
    ]

    new_keys = {}
    for key, name, example in keys_to_set:
        current = existing_keys.get(key, os.environ.get(key, ""))
        if current:
            masked = current[:8] + "..." + current[-4:] if len(current) > 12 else "***"
            prompt = f"{name} [{masked}]: "
        else:
            prompt = f"{name} (例: {example}): "

        value = input(prompt).strip()
        if value:
            new_keys[key] = value
        elif current:
            new_keys[key] = current

    # 写入 .env 文件
    if new_keys:
        with open(env_path, "w") as f:
            f.write("# Council API Keys\n")
            f.write("# Auto-generated by setup_api_keys.py\n\n")
            for key, value in new_keys.items():
                f.write(f"{key}={value}\n")

        print(f"\n✅ 已保存到 {env_path}")
        print("\n要加载这些 keys，运行:")
        print(f"  source {env_path}")
        print("  # 或")
        print("  export $(cat .env | xargs)")
    else:
        print("\n⚠️ 未设置任何 API key")

    return new_keys


def check_gcloud():
    """检查并提示安装 gcloud"""
    import shutil

    if shutil.which("gcloud"):
        print("\n✅ gcloud CLI 已安装")
        print("运行以下命令登录 Google Cloud:")
        print("  gcloud auth application-default login")
        return True
    else:
        print("\n⚠️ gcloud CLI 未安装")
        print("安装方法:")
        print("  # Ubuntu/Debian")
        print("  sudo apt-get install google-cloud-cli")
        print("  # 或下载: https://cloud.google.com/sdk/docs/install")
        return False


def main():
    print("\n🔑 Council 多模型 API 配置\n")

    # 1. 设置 API keys
    keys = setup_env_file()

    # 2. 检查 gcloud
    print("\n" + "-" * 40)
    check_gcloud()

    # 3. 验证
    print("\n" + "-" * 40)
    print("\n验证配置:")

    for key in ["ANTHROPIC_API_KEY", "OPENAI_API_KEY", "GEMINI_API_KEY"]:
        value = keys.get(key) or os.environ.get(key)
        status = "✅" if value else "❌"
        print(f"  {status} {key}")

    print("\n完成! 现在可以运行:")
    print("  python -m council.cli dev '你的任务'")


if __name__ == "__main__":
    main()
